# Generated by Django 4.1 on 2022-10-09 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='escala',
            name='equipment',
            field=models.CharField(choices=[('vtr', 'Viatura'), ('mto', 'Moto')], default='vtr', max_length=3, verbose_name='Equipment'),
        ),
    ]
