# Generated by Django 4.1 on 2022-10-09 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0002_escala_equipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escala',
            name='equipment',
            field=models.CharField(choices=[('vtr', 'Viatura'), ('mt', 'Moto')], default='vtr', max_length=3, verbose_name='Equipment'),
        ),
        migrations.AlterField(
            model_name='escala',
            name='group',
            field=models.CharField(choices=[('i', 'Grupo_1'), ('ii', 'Grupo_2'), ('iii', 'Grupo_3'), ('iv', 'Grupo_4')], default='i', max_length=3, verbose_name='Group'),
        ),
    ]
